dist: trusty

sudo: false

language: cpp

before_script:
  - mkdir build

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cppcheck
            - python-pip
      env:
       - TEST="linux-g++5"
       - COMPILERCXX="g++-5"
       - COMPILERC="gcc-5"
       - OPENSSL_VERSION=openssl-1.1.0
      script:
       - cd build
       - cmake -DBUILD_SSL=NO ..
       - make -j3 && make test	# j suppose to be based on number of processor...

    - os: linux
      compiler: clang
      env:
       - TEST="linux-clang"
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-5             #libstdc++5 required
      script:
       - cd build
       - cmake -DBUILD_SSL=NO ..
       - make -j3 && make test	# j suppose to be based on number of processor...

    - os: osx
      compiler: gcc
      env:
       - TEST="osx-gcc"
      script:
       - cd build
       - cmake -DBUILD_SSL=NO ..
       - make -j3 && make test	# j suppose to be based on number of processor...

    - os: osx
      compiler: clang
      env:
       - TEST="osx-clang"
      script:
       - cd build
       - cmake -DBUILD_SSL=NO ..
       - make -j3 && make test	# j suppose to be based on number of processor...

notifications:
  recipients:
    - rakib_mc12@yahoo.com
  email:
    on_success: change
    on_failure: always
