dist: trusty

sudo: false

language: cpp

before_script:
  - mkdir build

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
       - COMPILERCXX="g++-5"
       - COMPILERC="gcc-5"
       - OPENSSL_VERSION=openssl-1.1.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      script:
       - cd build
       - cmake -DBUILD_SSL=NO ..
       - make -j3 && make test	# j suppose to be based on number of processor...

    - os: linux
      compiler: clang
      env:
       - TEST="linux-clang"
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-5             #libstdc++5 required
      script:
       - cd build
       - cmake -DBUILD_SSL=NO ..
       - make -j3 && make test	# j suppose to be based on number of processor...

    - os: osx
      compiler: clang
      env:
       - TEST="osx-clang"
      script:
       - cd build
       - cmake -DBUILD_SSL=NO ..
       - make -j3 && make test	# j suppose to be based on number of processor...

    #
    # Documentation generation
    #
    - os: linux
      env:
       - TEST="Documentation"
      addons:
        apt:
          packages:
           - doxygen
      script:
       - doxygen > doxygen-output.log 2>&1
       - COUNT=`grep -rnw doxygen-output.log -e "warning:" | wc -l`
       - |
         if [[ "$COUNT" > "0" ]]; then
            # On ideal case we have to return error, for now just let user know
            echo "Documentation error found. Please take a look."
         fi

    #
    # cppcheck
    #
    - os: linux
      env:
       - TEST="cppcheck"
      addons:
        apt:
          packages:
           - cppcheck
      script:
       - cppcheck --enable=warning,style,performance,portability,unusedFunction --std=c++11 --verbose --error-exitcode=1 --language=c++ -I source/corvusoft/restbed/*.hpp source/corvusoft/restbed/detail/*.hpp source/corvusoft/restbed > cppcheck.log 2>&1
         # just print few of them...
       - |
               echo "Number of performance issue found: " `grep cppcheck.log -e performace|wc -l`
               echo "Number of style issue found: " `grep cppcheck.log -e style|wc -l`
               echo "Number of unused function: " `grep cppcheck.log -e unusedFunction|wc -l`


    # Code coverage based on gcov
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - lcov
      script:
       - cd build
       - cmake -DBUILD_SSL=NO -DBUILD_COVERAGE=ON ..
       - make -j3 && make gcov

notifications:
  recipients:
    - rakib_mc12@yahoo.com
  email:
    on_success: change
    on_failure: always
