dist: trusty

sudo: false

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
          - cppcheck
      env:
      - COMPILERCXX="g++-5"
      - COMPILERC="gcc-5"
      - OPENSSL_VERSION=openssl-1.1.0
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5             #libstdc++5 required
    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang
before_script:
  - cppcheck source 2>err.log      # collecting cpp check err stat
  - COUNT=`grep -w error err.log | wc -l`
  - if [[ "$COUNT" > "0" ]]; then
        echo "cppcheck failed.";
        exit -1;
    fi
  - if [ -n "$COMPILERC" ]; then export CC=$COMPILERC; fi
  - if [ -n "$COMPILERCXX" ]; then export CXX=$COMPILERCXX; fi 
  - mkdir build
  - cd build
  - cmake -DBUILD_SSL=NO ..

script: make -j3 && make test

notifications:
  recipients:
    - support@corvusoft.co.uk
  email:
    on_success: change
    on_failure: always
